import { Dimensions, StyleSheet } from "react-native";
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from "react-native-responsive-dimensions";

export const globalStyles = StyleSheet.create({
  twMain: {
    position: "absolute",
    width: responsiveWidth(100),
    height: responsiveHeight(100),
    borderRadius: responsiveWidth(0),
  },

  //Stater screen styling
  welcome_Image: {
    borderRadius: responsiveWidth(15),
    marginLeft: responsiveWidth(2),
    marginTop: responsiveHeight(3),
    backgroundColor: "rgba(0,0,0,0)",
    marginRight: responsiveWidth(2),
    position: "absolute",
    width: responsiveWidth(96),
    height: responsiveHeight(55),
    opacity: 1,
    marginEnd: responsiveWidth(4),
  },
  style_Just_Try: {
    marginLeft: responsiveWidth(30),
    marginTop: responsiveHeight(60),
    position: "absolute",
    fontFamily: "poppins-bold",
    //lineHeight: 114.99999761581421,
    textAlign: "center",
    letterSpacing: 0.1,
    color: "rgba(0,0,0,1)",
    fontSize: responsiveFontSize(3.5),
    textAlignVertical: "top",
    fontWeight: "bold",
  },
  style_design: {
    marginLeft: responsiveWidth(19),
    marginTop: responsiveHeight(66),
    position: "absolute",
    fontFamily: "poppins-bold",
    //lineHeight: 114.99999761581421,
    textAlign: "center",
    letterSpacing: 0.1,
    color: "rgba(0,0,0,1)",
    fontSize: responsiveFontSize(3),
    textAlignVertical: "top",
    fontWeight: "bold",
  },
  style_in_publishing: {
    marginLeft: responsiveWidth(10),
    marginTop: responsiveHeight(72),
    position: "absolute",
    //lineHeight: 114.99999761581421,
    textAlignVertical: "top",
  },
  in_pub_text: {
    width: responsiveWidth(80),
    height: responsiveHeight(25),
    fontFamily: "poppins-regular",
    textAlign: "center",
    letterSpacing: 0.1,
    color: "rgba(0,0,0,1)",
    fontSize: responsiveFontSize(2),
  },
  welcome_btn_Group: {
    position: "absolute",
    width: responsiveWidth(33),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(20),
    marginLeft: responsiveWidth(3),
    backgroundColor: "rgba(0,0,0,0)",
  },
  welocme_animationBtn: {
    marginTop: responsiveHeight(54.5),
    marginLeft: responsiveWidth(51),
    width: responsiveWidth(30),
    height: responsiveHeight(30),
    zIndex: 2,
  },
  Register_btn: {
    zIndex: 2,
    position: "absolute",
    width: responsiveWidth(48),
    height: responsiveHeight(8),
    marginTop: responsiveHeight(66),
    marginLeft: responsiveWidth(5),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(12),
  },
  register_SignUp: {
    marginTop: responsiveHeight(4),
    zIndex: 2,
    alignItems: "center",
    justifyContent: "center",
    height: responsiveHeight(10),
    backgroundColor: "rgba(24,154,180,1)",
    borderRadius: responsiveWidth(6),
  },
  Register_Text: {
    position: "absolute",
    width: responsiveWidth(29),
    height: responsiveHeight(9),
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(16),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    color: "white",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  Sign_in_btn: {
    position: "relative",
    width: responsiveWidth(53),
    height: responsiveHeight(8),
    marginTop: responsiveHeight(66),
    marginLeft: responsiveWidth(36),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(12),
    opacity: 1,
  },
  SignIn_Text: {
    position: "absolute",
    width: responsiveWidth(33),
    height: responsiveHeight(9),
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(22),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    color: "white",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },

  //Login page styling
  login_hello: {
    marginLeft: responsiveWidth(14),
    marginTop: responsiveHeight(7),
    position: "absolute",
    width: responsiveWidth(60),
    height: responsiveHeight(15),
    fontFamily: "poppins-bold",
    fontWeight: "bold",
    //lineHeight: 114.99999761581421,
    textAlign: "center",
    letterSpacing: 0.1,
    color: "rgb(1,1,1)",
    fontSize: responsiveFontSize(3.7),
    textAlignVertical: "top",
  },
  login_welcome_back: {
    position: "absolute",
    marginTop: responsiveHeight(23),
    width: responsiveWidth(60),
    height: responsiveHeight(18),
    justifyContent: "center",
    fontFamily: "poppins-regular",
    fontSize: responsiveFontSize(3),
    //lineHeight: 120.49999237060547,
    textAlign: "center",
    letterSpacing: 0.1,
    color: "rgba(0,0,0,1)",
  },

  //common text fields
  textInput: {
    marginLeft: responsiveWidth(8),
    marginTop: responsiveHeight(32),
    position: "absolute",
    width: responsiveWidth(85),
    height: responsiveHeight(10),
    opacity: 1,
    backgroundColor: "rgba(217,217,217,1)",
    borderRadius: responsiveWidth(6),
  },

  textInput_register: {
    marginLeft: responsiveWidth(2),
    width: responsiveWidth(85),
    height: responsiveHeight(10),
    opacity: 1,
    backgroundColor: "rgba(217,217,217,1)",
    borderRadius: responsiveWidth(6),
  },
  Recovery_Password: {
    marginLeft: responsiveWidth(48),
    marginTop: responsiveHeight(1),
    position: "absolute",
    //width: responsiveWidth(50),
    //height: responsiveHeight(20),
    fontFamily: "poppins-regular",
    fontSize: responsiveFontSize(2),
    color: "rgba(0,0,0,1)",
    //lineHeight: 120.49999237060547,
    textAlign: "right",
    letterSpacing: 0.1,
    textAlignVertical: "top",
    borderRadius: responsiveWidth(6),
  },

  //login button styling
  login_SignIn: {
    marginLeft: responsiveWidth(8),
    marginTop: responsiveHeight(62),
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    width: responsiveWidth(85),
    height: responsiveHeight(10),
    opacity: 1,
    backgroundColor: "rgba(24,154,180,1)",
    borderRadius: responsiveWidth(6),
  },
  Sign_in_Text: {
    fontSize: responsiveFontSize(2.5),
    color: "black",
    fontWeight: "bold",
  },

  login_or_continue: {
    marginTop: responsiveHeight(-10),
    textAlign: "center",
    textAlignVertical: "top",
    fontFamily: "poppins-regular",
    fontSize: responsiveFontSize(2),
    color: "rgba(0,0,0,1)",
  },
  style_google_icon: {
    marginLeft: responsiveWidth(6),
    opacity: 1,
    borderRadius: 0,
    backgroundColor: "rgba(0,0,0,0)",
  },

  style_Not_A_Member: {
    marginTop: responsiveHeight(92),
    marginLeft: responsiveWidth(23),
    position: "absolute",
    fontFamily: "poppins-regular",
    fontSize: responsiveFontSize(2),
  },
  // style_register: {
  //   marginTop: responsiveHeight(92),
  //   marginLeft: responsiveWidth(57),
  //   position: 'absolute',
  //   width: responsiveWidth(50),
  //   height: responsiveHeight(20),
  //   textAlign: 'center',
  //   textAlignVertical: 'top',
  //   fontSize: responsiveFontSize(2),
  //   fontFamily: "poppins-regular",
  //   Color: "purple",
  // },

  //register page styling
  register_hello: {
    marginLeft: responsiveWidth(49),
    marginTop: responsiveHeight(3),
    alignItems: "center",
    position: "absolute",
    fontFamily: "poppins-bold",
    fontWeight: "bold",
    textAlign: "center",
    fontSize: responsiveFontSize(3.3),
  },
  // register_SignUp: {
  //   marginLeft: responsiveWidth(8),
  //   marginTop: responsiveHeight(78),
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   position: 'absolute',
  //   width: responsiveWidth(85),
  //   height: responsiveHeight(10),
  //   opacity: 1,
  //   backgroundColor: "rgba(24,154,180,1)",
  //   borderRadius: responsiveWidth(6),
  // },
  // style_Login: {
  //   marginTop: responsiveHeight(92),
  //   marginLeft: responsiveWidth(67),
  //   position: 'absolute',
  //   width: responsiveWidth(50),
  //   height: responsiveHeight(20),
  //   textAlign: 'center',
  //   textAlignVertical: 'top',
  //   fontSize: responsiveFontSize(2),
  //   fontFamily: "poppins-regular",
  //   Color: "purple",
  // },
  // //first group of register page
  CitizenWarden_btn_Group: {
    width: Dimensions.get("window").width,
    marginTop: responsiveHeight(-45),
    marginLeft: responsiveWidth(3),
    backgroundColor: "rgba(0,0,0,0)",
  },

  //Top header styling
  Notifi_MenuIcon: {
    position: "absolute",
    width: responsiveWidth(35),
    height: responsiveHeight(25),
    marginTop: responsiveHeight(5.5),
    marginRight: responsiveWidth(6),
  },

  locationTop: {
    position: "absolute",
    marginLeft: responsiveWidth(34),
    marginTop: responsiveHeight(4),
    marginRight: responsiveWidth(6),
  },
  locationTop_Text: {
    width: responsiveWidth(30),
    height: responsiveHeight(10),
    fontFamily: "poppins-bold",
    fontSize: responsiveFontSize(2),
   // color: "black",
    textAlign: "center",
    letterSpacing: 0.1,
    textAlignVertical: "top",
  },

  //Profile portion with name styling
  tw_ProfileGroup2: {
    position: "absolute",
    width: responsiveWidth(30),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(14),
    marginLeft: responsiveWidth(5),
    backgroundColor: "rgba(0,0,0,0)",
  },
  tw_Profile_goodMorning: {
    position: "absolute",
    width: responsiveWidth(40),
    height: responsiveHeight(10),
    marginLeft: responsiveWidth(11),
    marginRight: responsiveWidth(6),
    marginTop: responsiveHeight(4),
    fontFamily: "poppins-regular",
    fontSize: responsiveFontSize(2),
    //color: "rgba(0,0,0,1)",
    textAlign: "center",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  tw_Profile_Name: {
    position: "absolute",
    width: responsiveWidth(40),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(9),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    fontSize: responsiveFontSize(2),
    //color: "rgba(0,0,0,1)",
    textAlign: "center",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  searchIcon: {
    position: "absolute",
    marginTop: responsiveHeight(15),
    marginLeft: responsiveWidth(85),
  },

  //warden ease traffic rectangle styling
  easeTraffic_Rect: {
    flex: 1,
    position: "absolute",
    width: responsiveWidth(92),
    height: responsiveHeight(20),
    borderRadius: responsiveWidth(9),
    opacity: 1,
    marginTop: responsiveHeight(24),
    marginLeft: responsiveWidth(4),
    marginRight: responsiveWidth(6),
   //backgroundColor: "rgba(10,76,118,1)",
  },
  letsEase_theTraffic: {
    position: "absolute",
    width: responsiveWidth(40),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(25),
    marginLeft: responsiveWidth(9),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    fontSize: responsiveFontSize(3),
    color: "rgba(255,255,255,1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },

  //View places btn styling
  viewPlaces_btn: {
    position: "absolute",
    width: responsiveWidth(33),
    height: responsiveHeight(6),
    marginTop: responsiveHeight(36),
    marginLeft: responsiveWidth(8),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(10),
    opacity: 1,
    //backgroundColor: "rgba(24,154,180,1)",
  },
  viewPlaces: {
    position: "absolute",
    width: responsiveWidth(34),
    height: responsiveHeight(6),
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(3),
    marginRight: responsiveWidth(6),
    alignContent: "center",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  viewPlaces_Text: {
    fontFamily: "poppins-regular",
    color: "white",
    fontSize: responsiveFontSize(2),
  },

  //Add challan and view complaint styling
  challan_Rect: {
    position: "absolute",
    width: responsiveWidth(45),
    height: responsiveHeight(19),
    marginTop: responsiveHeight(45),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(10),
    opacity: 1,
    //backgroundColor: "rgba(24,154,180,1)",
  },

  addView_Challan_Text: {
    position: "absolute",
    width: responsiveWidth(25),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(10),
    marginLeft: responsiveWidth(5),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    color: "rgba(255,255,255,1)",
    fontSize: responsiveFontSize(2.1),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  challanIcon: {},
  challanImage: {},

  //statistics and history styling
  hisStat_Group: {
    position: "absolute",
    width: responsiveWidth(33),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(-1),
    marginLeft: responsiveWidth(3),
    backgroundColor: "rgba(0,0,0,0)",
  },
  hisStat_btn: {
    position: "absolute",
    height: responsiveHeight(8),
    marginTop: responsiveHeight(66),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(12),
    opacity: 1,
  },
  hisStat_Text: {
    position: "absolute",
    height: responsiveHeight(9),
    marginTop: responsiveHeight(1),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    color: "rgba(255,255,255,1)",
    fontSize: responsiveFontSize(3),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },

  //bottom styling of warden
  bottomGroup: {
    position: "absolute",
    height: responsiveHeight(10),
    backgroundColor: "rgba(0,0,0,0)",
  },
  settingCircle: {
    position: "absolute",
    width: responsiveWidth(17),
    height: responsiveHeight(8),
    marginTop: responsiveHeight(75),
    marginLeft: responsiveWidth(4),
    marginRight: responsiveWidth(6),
    //backgroundColor: "rgba(24,154,180,1)",
    borderRadius: responsiveWidth(10),
  },
  setting_Text: {
    position: "absolute",
    width: responsiveWidth(16),
    height: responsiveHeight(3),
    marginTop: responsiveHeight(83),
    marginLeft: responsiveWidth(5),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
   // color: "rgba(0,0,0,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  settingIcon: {
    position: "absolute",
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(4),
  },
  placesCircle: {
    position: "absolute",
    width: responsiveWidth(17),
    height: responsiveHeight(8),
    marginTop: responsiveHeight(75),
    marginLeft: responsiveWidth(28),
    marginRight: responsiveWidth(6),
   // backgroundColor: "rgba(24,154,180,1)",
    borderRadius: responsiveWidth(10),
  },
  placesIcon: {
    position: "absolute",
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(4),
  },

  places_Text: {
    position: "absolute",
    width: responsiveWidth(16),
    height: responsiveHeight(3),
    marginTop: responsiveHeight(83),
    marginLeft: responsiveWidth(30),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
    //color: "rgba(0,0,0,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  rulesCircle: {
    position: "absolute",
    width: responsiveWidth(17),
    height: responsiveHeight(8),
    marginTop: responsiveHeight(75),
    marginLeft: responsiveWidth(52),
    marginRight: responsiveWidth(6),
    //backgroundColor: "rgba(24,154,180,1)",
    borderRadius: responsiveWidth(10),
  },
  rulesIcon: {
    position: "absolute",
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(4),
  },

  rules_Text: {
    position: "absolute",
    width: responsiveWidth(22),
    height: responsiveHeight(3),
    marginTop: responsiveHeight(83),
    marginLeft: responsiveWidth(50),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
    //color: "rgba(0,0,0,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  helpCircle: {
    position: "absolute",
    width: responsiveWidth(17),
    height: responsiveHeight(8),
    marginTop: responsiveHeight(75),
    marginLeft: responsiveWidth(75),
    marginRight: responsiveWidth(6),
   // backgroundColor: "rgba(24,154,180,1)",
    borderRadius: responsiveWidth(10),
  },
  helpIcon: {
    position: "absolute",
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(4),
  },

  help_Text: {
    position: "absolute",
    width: responsiveWidth(16),
    height: responsiveHeight(3),
    marginTop: responsiveHeight(83),
    marginLeft: responsiveWidth(78.5),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
    //color: "rgba(0,0,0,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  map: {
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
  },
  //add challan screen styling
  challan_TopText: {
    position: "absolute",
    marginLeft: responsiveWidth(12.5),
    marginTop: responsiveHeight(2.5),
    fontFamily: "poppins-bold",
    fontWeight: "bold",
    fontSize: responsiveFontSize(4),
    //lineHeight: 120.49999237060547,
    textAlign: "center",
    letterSpacing: 0.1,
    color: "rgba(0,0,0,1)",
    textAlignVertical: "top",
  },
  submitChallan_btn: {
    marginLeft: responsiveWidth(62),
    marginTop: responsiveHeight(85),
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    width: responsiveWidth(30),
    height: responsiveHeight(8),
    opacity: 1,
    //backgroundColor: "rgba(24,154,180,1)",
    borderRadius: responsiveWidth(6),
  },
  submitChallan_Text: {
    fontSize: responsiveFontSize(2.3),
    fontStyle: "normal",
    fontWeight: "bold",
  },

  /*citizen screen styling*/
  itsEasy_toPay: {
    position: "absolute",
    width: responsiveWidth(55),
    height: responsiveHeight(20),
    marginTop: responsiveHeight(25),
    marginLeft: responsiveWidth(9),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    fontSize: responsiveFontSize(3),
    color: "rgba(255,255,255,1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  payChallan_Rect: {
    position: "absolute",
    width: responsiveWidth(45),
    height: responsiveHeight(29),
    marginTop: responsiveHeight(45),
    marginLeft: responsiveWidth(4),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(10),
    opacity: 1,
    //backgroundColor: "rgba(24,154,180,1)",
  },
  payChallan_Text: {
    position: "absolute",
    width: responsiveWidth(35),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(15),
    marginLeft: responsiveWidth(7),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    color: "rgba(255,255,255,1)",
    fontSize: responsiveFontSize(3.5),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },

  fileHistory_Complaints_Rect: {
    position: "absolute",
    width: responsiveWidth(45),
    height: responsiveHeight(14),
    marginLeft: responsiveWidth(51),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(10),
    opacity: 1,
   // backgroundColor: "rgba(24,154,180,1)",
  },
  fileHistoryComplaints_Text: {
    position: "absolute",
    width: responsiveWidth(29),
    height: responsiveHeight(9),
    marginTop: responsiveHeight(5),
    //marginRight: responsiveWidth(0),
    fontFamily: "poppins-bold",
    color: "rgba(255,255,255,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },

  //adding challan second screen styling
  challanSecond_Rect: {
    flex: 1,
    position: "absolute",
    width: responsiveWidth(92),
    height: responsiveHeight(94),
    borderRadius: responsiveWidth(9),
    opacity: 1,
    marginTop: responsiveHeight(5),
    marginLeft: responsiveWidth(4),
    marginRight: responsiveWidth(6),
  },
  challanSecond_Group: {
    position: "absolute",
    width: responsiveWidth(33),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(0),
    marginLeft: responsiveWidth(0),
  },
  challanNum_Text: {
    position: "absolute",
    width: responsiveWidth(20),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(9),
    marginLeft: responsiveWidth(8),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
    color: "white",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  vehicleDetail_Text: {
    position: "absolute",
    width: responsiveWidth(20),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(20),
    marginLeft: responsiveWidth(8),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
    color: "white",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  regNum_Text: {
    position: "absolute",
    width: responsiveWidth(27),
    height: responsiveHeight(9),
    marginTop: responsiveHeight(31),
    marginLeft: responsiveWidth(8),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
    color: "white",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  amount_Text: {
    position: "absolute",
    width: responsiveWidth(20),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(44.5),
    marginLeft: responsiveWidth(8),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
    color: "white",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  dateTime_Text: {
    position: "absolute",
    width: responsiveWidth(20),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(57),
    marginLeft: responsiveWidth(8),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
    color: "white",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  location_Text: {
    position: "absolute",
    width: responsiveWidth(20),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(69),
    marginLeft: responsiveWidth(8),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
    color: "white",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  dueDate_Text: {
    position: "absolute",
    width: responsiveWidth(20),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(79),
    marginLeft: responsiveWidth(8),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
    color: "white",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  challanNum_TextInput: {
    marginLeft: responsiveWidth(32),
    marginTop: responsiveHeight(7.5),
    position: "absolute",
    width: responsiveWidth(60),
    height: responsiveHeight(8),
    opacity: 1,
    backgroundColor: "rgba(217,217,217,1)",
    color: "gray",
  },
  vehicleDetail_TextInput: {
    marginLeft: responsiveWidth(32),
    marginTop: responsiveHeight(18),
    position: "absolute",
    width: responsiveWidth(60),
    height: responsiveHeight(8),
    opacity: 1,
    backgroundColor: "rgba(217,217,217,1)",
    color: "gray",
  },
  regNum_TextInput: {
    marginLeft: responsiveWidth(32),
    marginTop: responsiveHeight(29),
    position: "absolute",
    width: responsiveWidth(60),
    height: responsiveHeight(8),
    opacity: 1,
    backgroundColor: "rgba(217,217,217,1)",
  },
  amount_TextInput: {
    marginLeft: responsiveWidth(32),
    marginTop: responsiveHeight(40),
    position: "absolute",
    width: responsiveWidth(60),
    height: responsiveHeight(8),
    opacity: 1,
    backgroundColor: "rgba(217,217,217,1)",
    color: "gray",
  },
  dateTime_TextInput: {
    marginLeft: responsiveWidth(32),
    marginTop: responsiveHeight(55),
    position: "absolute",
    width: responsiveWidth(60),
    height: responsiveHeight(8),
    opacity: 1,
    backgroundColor: "rgba(217,217,217,1)",
    color: "gray",
  },
  location_TextInput: {
    marginLeft: responsiveWidth(32),
    marginTop: responsiveHeight(67),
    position: "absolute",
    width: responsiveWidth(60),
    height: responsiveHeight(8),
    opacity: 1,
    backgroundColor: "rgba(217,217,217,1)",
  },
  dueDate_TextInput: {
    marginLeft: responsiveWidth(32),
    marginTop: responsiveHeight(77),
    position: "absolute",
    width: responsiveWidth(60),
    height: responsiveHeight(8),
    opacity: 1,
    backgroundColor: "rgba(217,217,217,1)",
    borderRadius: responsiveWidth(6),
    color: "gray",
  },
  lineStyle: {
    position: "absolute",
    width: responsiveWidth(77),
    height: responsiveHeight(0),
    marginLeft: responsiveWidth(10),
    marginTop: responsiveHeight(52.5),
    borderWidth: responsiveWidth(0.5),
    borderStyle: "solid",
    borderColor: "rgba(243, 242, 252, 1)",
  },
  dueDate_Icon: {
    position: "absolute",
    width: responsiveWidth(25),
    height: responsiveHeight(20),
    marginLeft: responsiveWidth(82),
    marginTop: responsiveHeight(80.5),
    marginRight: responsiveWidth(6),
  },
  printChallan_btn: {
    marginLeft: responsiveWidth(33),
    marginTop: responsiveHeight(89),
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    width: responsiveWidth(30),
    height: responsiveHeight(8),
    opacity: 1,
    borderRadius: responsiveWidth(6),
  },

  //Payment screen styling

  pendingChallan: {
    flex: 1,
    position: "absolute",
    width: responsiveWidth(92),
    height: responsiveHeight(18),
    borderRadius: responsiveWidth(9),
    opacity: 1,
    marginTop: responsiveHeight(14),
    marginLeft: responsiveWidth(4),
    marginRight: responsiveWidth(6),
    backgroundColor: "rgba(24,154,180,1)",
  },
  camera: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: responsiveWidth(20),
  },
  cameraButtns: {
    position: "relative",
    width: responsiveWidth(95),
    height: responsiveHeight(8),
   //backgroundColor: "rgba(24,154,180,1)",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: responsiveWidth(6),
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(0.5),
  },
  pendingChallanImage: {
    marginTop: responsiveHeight(1.5),
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    width: responsiveWidth(30),
    height: responsiveHeight(15),
    marginLeft: responsiveWidth(3),
    backgroundColor: "rgba(217,217,217,1)",
    borderRadius: responsiveWidth(6),
  },
  NotificationItem: {
    alignItems: "center",
    justifyContent: "center",
    width: responsiveWidth(92),
    marginTop: responsiveHeight(2.5),
   // height: responsiveHeight(10),
    marginVertical: responsiveHeight(-1),
    marginHorizontal: responsiveWidth(4),
    borderRadius: responsiveWidth(6),
    //backgroundColor: "rgba(217,217,217,1)",
  },
  SearchBarStyling: {
    width: responsiveWidth(100),
    height: responsiveHeight(7),
  },
  NotificationBadge: {
    backgroundColor: "red",
    borderRadius: responsiveWidth(5),
    fontFamily: "poppins-regular",
    fontSize: responsiveFontSize(1.8),
    width: responsiveWidth(5),
    height: responsiveHeight(2.6),
    textAlign: "center",
    color: "white",
    marginTop: responsiveHeight(-1.5),
  },
  header: {
    height: 105,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    //backgroundColor: "rgba(10,76,118,1)",
  },
  headerText: {
    fontFamily: "poppins-bold",
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
  },
});
