import { Dimensions, StyleSheet } from "react-native";
import {
  responsiveFontSize, responsiveHeight, responsiveWidth
} from "react-native-responsive-dimensions";


export const globalStyles = StyleSheet.create({

  twMain: {
    position: "absolute",
    width: responsiveWidth(100),
    height: responsiveHeight(100),
    borderRadius: responsiveWidth(0),
  },

  //Stater screen styling
  welcome_Image: {
    borderRadius: responsiveWidth(15),
    marginLeft: responsiveWidth(2),
    marginTop: responsiveHeight(3),
    backgroundColor: 'rgba(0,0,0,0)',
    marginRight: responsiveWidth(2),
    position: 'absolute',
    width: responsiveWidth(96),
    height: responsiveHeight(55),
    opacity: 1,
    marginEnd: responsiveWidth(4),
  },
  style_Just_Try: {
    marginLeft: responsiveWidth(30),
    marginTop: responsiveHeight(60),
    position: 'absolute',
    width: responsiveWidth(60),
    height: responsiveHeight(15),
    fontFamily: "poppins-bold",
    lineheight: 114.99999761581421,
    textalign: 'center',
    letterspacing: 0.1,
    color: 'rgba(0,0,0,1)',
    fontSize: responsiveFontSize(3.5),
    textalignVertical: 'top', textDecoration: 'none',
    fontWeight: 'bold'
  },
  style_design: {
    marginLeft: responsiveWidth(23),
    marginTop: responsiveHeight(65),
    position: 'absolute',
    width: responsiveWidth(60),
    height: responsiveHeight(15),
    fontFamily: "poppins-bold",
    lineheight: 114.99999761581421,
    textalign: 'center',
    letterspacing: 0.1,
    color: 'rgba(0,0,0,1)',
    fontSize: responsiveFontSize(3.5),
    textalignVertical: 'top',
    textDecoration: 'none',
    fontWeight: 'bold'
  },
  style_in_publishing: {
    marginLeft: responsiveWidth(10),
    marginTop: responsiveHeight(72),
    position: 'absolute',
    lineheight: 114.99999761581421,
    textalignVertical: 'top',
    textDecoration: 'none',
  },
  in_pub_text: {
    width: responsiveWidth(80),
    height: responsiveHeight(25),
    fontFamily: "poppins-regular",
    textalign: 'center',
    textAlign: 'center',
    letterspacing: 0.1,
    color: 'rgba(0,0,0,1)',
    fontSize: responsiveFontSize(2),
  },
  welcome_btn_Group: {
    position: "absolute",
    width: responsiveWidth(33),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(20),
    marginLeft: responsiveWidth(3),
    backgroundColor: "rgba(0,0,0,0)",
  },
  Register_btn: {
    backgroundColor: 'rgba(217,217,217,1)',
    zIndex: 2,
    position: "absolute",
    width: responsiveWidth(48),
    height: responsiveHeight(8),
    marginTop: responsiveHeight(66),
    marginLeft: responsiveWidth(5),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(12),
  },
  Register_Text: {
    position: "absolute",
    width: responsiveWidth(29),
    height: responsiveHeight(9),
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(16),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    color: "rgba(0,0,0,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  Sign_in_btn: {
    backgroundColor: 'rgba(215,152,246,1)',
    position: 'relative',
    width: responsiveWidth(53),
    height: responsiveHeight(8),
    marginTop: responsiveHeight(66),
    marginLeft: responsiveWidth(36),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(12),
    opacity: 1,
  },
  SignIn_Text: {
    position: "absolute",
    width: responsiveWidth(33),
    height: responsiveHeight(9),
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(22),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    color: "rgba(255,255,255,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },

  //Login page styling
  login_hello: {
    marginLeft: responsiveWidth(14),
    marginTop: responsiveHeight(7),
    position: 'absolute',
    width: responsiveWidth(60),
    height: responsiveHeight(15),
    fontfamily: 'poppins-bold',
    fontWeight: 'bold',
    lineheight: 114.99999761581421,
    textalign: 'center',
    letterspacing: 0.1,
    color: 'rgb(1,1,1)',
    fontSize: responsiveFontSize(3.7),
    textalignVertical: 'top',
  },
  login_welcome_back: {
    position: 'absolute',
    marginLeft: responsiveWidth(15),
    marginTop: responsiveHeight(23),
    width: responsiveWidth(60),
    height: responsiveHeight(18),
    justifyContent: 'center',
    fontfamily: 'poppins-regular',
    fontstyle: 'normal',
    fontSize: responsiveFontSize(3),
    lineheight: 120.49999237060547,
    textalign: 'center',
    letterspacing: 0.1,
    color: 'rgba(0,0,0,1)',
    textDecorationLine: 'none',
    textAlignVertical: 'top',
  },

  //common text fields
  textInput_1: {
    marginLeft: responsiveWidth(8),
    marginTop: responsiveHeight(32),
    position: 'absolute',
    width: responsiveWidth(85),
    height: responsiveHeight(10),
    opacity: 1,
    backgroundColor: 'rgba(217,217,217,1)',
    borderRadius: responsiveWidth(6),
  },
  textInput_2: {
    marginLeft: responsiveWidth(8),
    marginTop: responsiveHeight(44),
    position: 'absolute',
    width: responsiveWidth(85),
    height: responsiveHeight(10),
    opacity: 1,
    background: '#D9D9D9',
    backgroundColor: 'rgba(217,217,217,1)',
    borderRadius: responsiveWidth(6),
  },
  textInput_3: {
    marginLeft: responsiveWidth(8),
    marginTop: responsiveHeight(56),
    position: 'absolute',
    width: responsiveWidth(85),
    height: responsiveHeight(10),
    opacity: 1,
    background: '#D9D9D9',
    backgroundColor: 'rgba(217,217,217,1)',
    borderRadius: responsiveWidth(6),
  },
  textInput_4: {
    marginLeft: responsiveWidth(8),
    marginTop: responsiveHeight(68),
    position: 'absolute',
    width: responsiveWidth(85),
    height: responsiveHeight(10),
    opacity: 1,
    background: '#D9D9D9',
    backgroundColor: 'rgba(217,217,217,1)',
    borderRadius: responsiveWidth(6),
  },
  Recovery_Password: {
    marginLeft: responsiveWidth(48),
    marginTop: responsiveHeight(55.5),
    position: 'absolute',
    width: responsiveWidth(50),
    height: responsiveHeight(20),
    fontFamily: "poppins-regular",
    fontSize: responsiveFontSize(2),
    color: 'rgba(0,0,0,1)',
    lineheight: 120.49999237060547,
    textalign: 'right',
    letterspacing: 0.1,
    textalignVertical: 'top',
    borderRadius: responsiveWidth(6),
  },

  //login button styling
  login_SignIn: {
    marginLeft: responsiveWidth(8),
    marginTop: responsiveHeight(62),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    width: responsiveWidth(85),
    height: responsiveHeight(10),
    opacity: 1,
    backgroundColor: 'rgba(215,152,246,1)',
    borderRadius: responsiveWidth(6),
  },
  Sign_in_Text: {
    fontSize: responsiveFontSize(2.3),
    fontstyle: 'noramal',
  },

  login_or_continue: {
    marginTop: responsiveHeight(75),
    marginLeft: responsiveWidth(34),
    position: 'absolute',
    width: responsiveWidth(50),
    height: responsiveHeight(20),
    textalign: 'center',
    textalignVertical: 'top',
    fontFamily: "poppins-regular",
    fontSize: responsiveFontSize(2),
    color: 'rgba(0,0,0,1)',
  },
  style_google_icon: {
    marginLeft: responsiveWidth(15),
    marginTop: responsiveHeight(84),
    width: responsiveWidth(42),
    height: responsiveHeight(42),
    opacity: 1,
    borderRadius: 0,
    backgroundColor: 'rgba(0,0,0,0)',
  },
  style_apple_icon: {
    marginLeft: responsiveWidth(-12),
    marginTop: responsiveHeight(84),
    width: responsiveWidth(42),
    height: responsiveHeight(42),
    opacity: 1,
    borderRadius: responsiveWidth(0),
    backgroundColor: 'rgba(0,0,0,0)',
  },
  style_facebook_icon: {
    marginLeft: responsiveWidth(-12),
    marginTop: responsiveHeight(84),
    width: responsiveWidth(42),
    height: responsiveHeight(42),
    opacity: 1,
    borderRadius: responsiveWidth(0),
    backgroundColor: 'rgba(0,0,0,0)',
  },
  style_Not_A_Member: {
    marginTop: responsiveHeight(92),
    marginLeft: responsiveWidth(21),
    position: 'absolute',
    width: responsiveWidth(50),
    height: responsiveHeight(20),
    textalign: 'center',
    textalignVertical: 'top',
    fontFamily: "poppins-regular",
    fontSize: responsiveFontSize(2),
    color: 'rgba(0,0,0,1)',
  },
  style_register: {
    marginTop: responsiveHeight(92),
    marginLeft: responsiveWidth(57),
    position: 'absolute',
    width: responsiveWidth(50),
    height: responsiveHeight(20),
    textalign: 'center',
    textalignVertical: 'top',
    fontSize: responsiveFontSize(2),
    fontFamily: "poppins-regular",
    Color: "purple",
  },

  //register page styling
  register_hello: {
    marginLeft: responsiveWidth(14),
    marginTop: responsiveHeight(3),
    position: 'absolute',
    width: responsiveWidth(60),
    height: responsiveHeight(15),
    fontfamily: 'poppins-bold',
    fontWeight: 'bold',
    lineheight: 114.99999761581421,
    textalign: 'center',
    letterspacing: 0.1,
    color: 'rgb(1,1,1)',
    fontSize: responsiveFontSize(3.7),
    textalignVertical: 'top',
  },
  register_SignUp: {
    marginLeft: responsiveWidth(8),
    marginTop: responsiveHeight(80),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    width: responsiveWidth(85),
    height: responsiveHeight(10),
    opacity: 1,
    backgroundColor: 'rgba(215,152,246,1)',
    borderRadius: responsiveWidth(6),
  },
  style_Login: {
    marginTop: responsiveHeight(92),
    marginLeft: responsiveWidth(67),
    position: 'absolute',
    width: responsiveWidth(50),
    height: responsiveHeight(20),
    textalign: 'center',
    textalignVertical: 'top',
    fontSize: responsiveFontSize(2),
    fontFamily: "poppins-regular",
    Color: "purple",
  },
  //first group of register page
  CitizenWarden_btn_Group: {
    position: "absolute",
    width: responsiveWidth(33),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(-44),
    marginLeft: responsiveWidth(3),
    backgroundColor: "rgba(0,0,0,0)",
  },

  //Top header styling
  menuIcon: {
    position: "absolute",
    width: responsiveWidth(14),
    height: responsiveHeight(30),
    marginTop: responsiveHeight(6),
    marginLeft: responsiveWidth(6),
    marginRight: responsiveWidth(6),
  },
  notificationIcon: {
    position: "absolute",
    width: responsiveWidth(25),
    height: responsiveHeight(20),
    marginLeft: responsiveWidth(85),
    marginTop: responsiveHeight(5),
    marginRight: responsiveWidth(6),
  },
  locationTop: {
    position: "absolute",
    marginLeft: responsiveWidth(34),
    marginTop: responsiveHeight(4),
    marginRight: responsiveWidth(6),
  },
  locationTop_Text: {
    width: responsiveWidth(30),
    height: responsiveHeight(10),
    fontFamily: "poppins-bold",
    fontSize: responsiveFontSize(2),
    color: "black",
    textAlign: "center",
    letterSpacing: 0.1,
    textAlignVertical: "top",
    textDecorationLine: "none",
  },

  //Profile portion with name styling
  tw_ProfileGroup2: {
    position: "absolute",
    width: responsiveWidth(30),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(14),
    marginLeft: responsiveWidth(5),
    backgroundColor: "rgba(0,0,0,0)",
  },
  tw_Profile_goodMorning: {
    position: "absolute",
    width: responsiveWidth(40),
    height: responsiveHeight(10),
    marginLeft: responsiveWidth(11),
    marginRight: responsiveWidth(6),
    marginTop: responsiveHeight(4),
    fontFamily: "poppins-regular",
    fontSize: responsiveFontSize(2),
    color: "rgba(0,0,0,1)",
    textAlign: "center",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  tw_Profile_Name: {
    position: "absolute",
    width: responsiveWidth(30),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(9),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    fontSize: responsiveFontSize(2),
    color: "rgba(0,0,0,1)",
    textAlign: "center",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  searchIcon: {
    position: "absolute",
    marginTop: responsiveHeight(15),
    marginLeft: responsiveWidth(85),
  },

  //warden ease traffic rectangle styling
  easeTraffic_Rect: {
    flex: 1,
    position: "absolute",
    width: responsiveWidth(92),
    height: responsiveHeight(20),
    borderRadius: responsiveWidth(9),
    opacity: 1,
    marginTop: responsiveHeight(24),
    marginLeft: responsiveWidth(4),
    marginRight: responsiveWidth(6),
    backgroundColor: "rgba(24,154,180,1)",
  },
  letsEase_theTraffic: {
    position: "absolute",
    width: responsiveWidth(40),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(25),
    marginLeft: responsiveWidth(9),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    fontSize: responsiveFontSize(3),
    color: "rgba(255,255,255,1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },

  //View places btn styling
  viewPlaces_btn: {
    position: "absolute",
    width: responsiveWidth(33),
    height: responsiveHeight(6),
    marginTop: responsiveHeight(36),
    marginLeft: responsiveWidth(8),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(10),
    opacity: 1,
    backgroundColor: "rgba(47,67,78,1)",
  },
  viewPlaces: {
    position: "absolute",
    width: responsiveWidth(34),
    height: responsiveHeight(6),
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(3),
    marginRight: responsiveWidth(6),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1
  },
  viewPlaces_Text: {
    fontFamily: "poppins-regular",
    color: "rgba(217,217,217,1)",
    fontSize: responsiveFontSize(2),
  },
  // carImage: {
  //   position: "absolute",
  //   width: 265,
  //   height: 254,
  //   borderRadius: 0,
  //   opacity: 1,
  //   left: 173,
  //   right: "auto",
  //   top: 117,
  //   bottom: "auto",
  //   transform: [{ translateX: 0 }, { translateY: 0 }, { rotate: "0deg" }],
  //   backgroundColor: "rgba(0,0,0,0)",
  // },


  //Add challan and view complaint styling
  addChallan_Rect: {
    position: "absolute",
    width: responsiveWidth(45),
    height: responsiveHeight(19),
    marginTop: responsiveHeight(45),
    marginLeft: responsiveWidth(4),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(10),
    opacity: 1,
    backgroundColor: "rgba(33,182,168,1)",
  },
  addChallan_Text: {
    position: "absolute",
    width: responsiveWidth(25),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(10),
    marginLeft: responsiveWidth(5),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    color: "rgba(255,255,255,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  challanIcon: {

  },
  challanImage: {

  },
  viewComplaints_Rect: {
    position: "absolute",
    width: responsiveWidth(45),
    height: responsiveHeight(19),
    marginTop: responsiveHeight(45),
    marginLeft: responsiveWidth(51),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(10),
    opacity: 1,
    backgroundColor: "rgba(33,182,168,1)",
  },
  viewComplaints_Text: {
    position: "absolute",
    width: responsiveWidth(29),
    height: responsiveHeight(9),
    marginTop: responsiveHeight(10),
    marginLeft: responsiveWidth(5),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    color: "rgba(255,255,255,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },

  //statistics and history styling
  hisStat_Group: {
    position: "absolute",
    width: responsiveWidth(33),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(-1),
    marginLeft: responsiveWidth(3),
    backgroundColor: "rgba(0,0,0,0)",
  },
  history_btn: {
    position: "absolute",
    width: responsiveWidth(54),
    height: responsiveHeight(8),
    marginTop: responsiveHeight(66),
    marginLeft: responsiveWidth(1),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(12),
    opacity: 1,
    backgroundColor: "rgba(24,154,180,1)",
  },
  history_Text: {
    position: "absolute",
    width: responsiveWidth(29),
    height: responsiveHeight(9),
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(7),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    color: "rgba(255,255,255,1)",
    fontSize: responsiveFontSize(3),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  statistic_btn: {
    position: "absolute",
    width: responsiveWidth(53),
    height: responsiveHeight(8),
    marginTop: responsiveHeight(66),
    marginLeft: responsiveWidth(40),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(12),
    opacity: 1,
    backgroundColor: "rgba(33,182,168,1)",
  },
  statistics_Text: {
    position: "absolute",
    width: responsiveWidth(33),
    height: responsiveHeight(9),
    marginTop: responsiveHeight(1),
    marginLeft: responsiveWidth(11),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    color: "rgba(255,255,255,1)",
    fontSize: responsiveFontSize(3),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },

  //bottom styling of warden
  bottomGroup: {
    position: "absolute",
    width: responsiveWidth(35),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(-1),
    marginLeft: responsiveWidth(2),
    backgroundColor: "rgba(0,0,0,0)",
  },
  settingCircle: {
    position: "absolute",
    width: responsiveWidth(17),
    height: responsiveHeight(8),
    marginTop: responsiveHeight(75),
    marginLeft: responsiveWidth(4),
    marginRight: responsiveWidth(6),
    backgroundColor: "rgba(33,182,168,1)",
    borderRadius: responsiveWidth(10),
  },
  setting_Text: {
    position: "absolute",
    width: responsiveWidth(16),
    height: responsiveHeight(3),
    marginTop: responsiveHeight(83),
    marginLeft: responsiveWidth(5),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
    color: "rgba(0,0,0,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  settingIcon: {
    position: "absolute",
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(4),
  },
  placesCircle: {
    position: "absolute",
    width: responsiveWidth(17),
    height: responsiveHeight(8),
    marginTop: responsiveHeight(75),
    marginLeft: responsiveWidth(28),
    marginRight: responsiveWidth(6),
    backgroundColor: "rgba(33,182,168,1)",
    borderRadius: responsiveWidth(10),
  },
  placesIcon: {
    position: "absolute",
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(4),
  },

  places_Text: {
    position: "absolute",
    width: responsiveWidth(16),
    height: responsiveHeight(3),
    marginTop: responsiveHeight(83),
    marginLeft: responsiveWidth(30),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
    color: "rgba(0,0,0,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  rulesCircle: {
    position: "absolute",
    width: responsiveWidth(17),
    height: responsiveHeight(8),
    marginTop: responsiveHeight(75),
    marginLeft: responsiveWidth(52),
    marginRight: responsiveWidth(6),
    backgroundColor: "rgba(33,182,168,1)",
    borderRadius: responsiveWidth(10),
  },
  rulesIcon: {
    position: "absolute",
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(4),
  },

  rules_Text: {
    position: "absolute",
    width: responsiveWidth(16),
    height: responsiveHeight(3),
    marginTop: responsiveHeight(83),
    marginLeft: responsiveWidth(55),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
    color: "rgba(0,0,0,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  helpCircle: {
    position: "absolute",
    width: responsiveWidth(17),
    height: responsiveHeight(8),
    marginTop: responsiveHeight(75),
    marginLeft: responsiveWidth(75),
    marginRight: responsiveWidth(6),
    backgroundColor: "rgba(33,182,168,1)",
    borderRadius: responsiveWidth(10),
  },
  helpIcon: {
    position: "absolute",
    marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(4),
  },

  help_Text: {
    position: "absolute",
    width: responsiveWidth(16),
    height: responsiveHeight(3),
    marginTop: responsiveHeight(83),
    marginLeft: responsiveWidth(78),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-regular",
    color: "rgba(0,0,0,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  map: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
  //add challan screen styling
  addChallan: {
    position: 'absolute',
    marginLeft: responsiveWidth(12),
    marginTop: responsiveHeight(2.5),
    fontfamily: 'poppins-bold',
    fontWeight: 'bold',
    fontSize: responsiveFontSize(4),
    lineheight: 120.49999237060547,
    textalign: 'center',
    letterspacing: 0.1,
    color: 'rgba(0,0,0,1)',
    textDecorationLine: 'none',
    textAlignVertical: 'top',
  },
  addCamera_Rect: {
    flex: 1,
    position: "absolute",
    width: responsiveWidth(92),
    height: responsiveHeight(20),
    borderRadius: responsiveWidth(9),
    opacity: 1,
    marginTop: responsiveHeight(14),
    marginLeft: responsiveWidth(4),
    marginRight: responsiveWidth(6),
    backgroundColor: "rgba(215,152,246,1)",
  },
  addChallan_Fields_Group: {
    position: "absolute",
    width: responsiveWidth(33),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(5),
    marginLeft: responsiveWidth(0),
    backgroundColor: "rgba(0,0,0,0)",
  },
  submitChallan_btn: {
    marginLeft: responsiveWidth(62),
    marginTop: responsiveHeight(85),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    width: responsiveWidth(30),
    height: responsiveHeight(8),
    opacity: 1,
    backgroundColor: 'rgba(215,152,246,1)',
    borderRadius: responsiveWidth(6),
  },
  submitChallan_Text: {
    fontSize: responsiveFontSize(2.3),
    fontstyle: 'noramal',
    fontWeight: 'bold',
  },

  /*citizen screen styling*/
  itsEasy_toPay:{
    position: "absolute",
    width: responsiveWidth(55),
    height: responsiveHeight(20),
    marginTop: responsiveHeight(25),
    marginLeft: responsiveWidth(9),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    fontSize: responsiveFontSize(3),
    color: "rgba(255,255,255,1)",
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  payChallan_Rect:{
    position: "absolute",
    width: responsiveWidth(45),
    height: responsiveHeight(29),
    marginTop: responsiveHeight(45),
    marginLeft: responsiveWidth(4),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(10),
    opacity: 1,
    backgroundColor: "rgba(33,182,168,1)",
  },
  payChallan_Text:{
    position: "absolute",
    width: responsiveWidth(35),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(13),
    marginLeft: responsiveWidth(7),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    color: "rgba(255,255,255,1)",
    fontSize: responsiveFontSize(3),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },

  fileComplaints_Rect:{
    position: "absolute",
    width: responsiveWidth(45),
    height: responsiveHeight(14),
    marginTop: responsiveHeight(45),
    marginLeft: responsiveWidth(51),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(10),
    opacity: 1,
    backgroundColor: "rgba(33,182,168,1)",
  },
  fileComplaints_Text:{
    position: "absolute",
    width: responsiveWidth(29),
    height: responsiveHeight(9),
    marginTop: responsiveHeight(5),
    marginLeft: responsiveWidth(12),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    color: "rgba(255,255,255,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  challanHistory_Rect:{
    position: "absolute",
    width: responsiveWidth(45),
    height: responsiveHeight(14),
    marginTop: responsiveHeight(60),
    marginLeft: responsiveWidth(51),
    marginRight: responsiveWidth(6),
    borderRadius: responsiveWidth(10),
    opacity: 1,
    backgroundColor: "rgba(33,182,168,1)",
  },
  challanHistory_Text:{
    position: "absolute",
    width: responsiveWidth(29),
    height: responsiveHeight(9),
    marginTop: responsiveHeight(5),
    marginLeft: responsiveWidth(20),
    marginRight: responsiveWidth(6),
    fontFamily: "poppins-bold",
    color: "rgba(255,255,255,1)",
    fontSize: responsiveFontSize(2),
    textAlign: "left",
    textAlignVertical: "top",
    letterSpacing: 0.1,
  },
  bottomGroup_Edited:{
    position: "absolute",
    width: responsiveWidth(35),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(0),
    marginLeft: responsiveWidth(2),
    backgroundColor: "rgba(0,0,0,0)",
  },
  //adding challan second screen styling
  challanSecond_Rect:{
    flex: 1,
    position: "absolute",
    width: responsiveWidth(92),
    height: responsiveHeight(94),
    borderRadius: responsiveWidth(9),
    opacity: 1,
    marginTop: responsiveHeight(5),
    marginLeft: responsiveWidth(4),
    marginRight: responsiveWidth(6),
    backgroundColor: "rgba(215,152,246,1)",
  },
  challanSecond_Fields_Group:{
    position: "absolute",
    width: responsiveWidth(33),
    height: responsiveHeight(10),
    marginTop: responsiveHeight(5),
    marginLeft: responsiveWidth(0),
    backgroundColor: "rgba(0,0,0,0)",
  }
});
